version: '3.4'

services:
  pms:
    image: lb2.ectivisecloud.com/pms:latest
    # image: pms
    # restart: always
    # volumes:
    #   - ./logs/all.log:/app/all.log:rw
    # environment:
    #   # - DEBUG=True
    #   - SLEEP=2.5
    build:
      context: .
      dockerfile: ./Dockerfile

